server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET TIME ZONE 'UTC'"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: "*"