server:
  port: 8082

spring:
  application:
    name: finance-service

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/financedb?authSource=admin
      database: financedb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

management:
  endpoints:
    web:
      exposure:
        include: "*"